### ISSUE TITLE
Error Access the Graphql Api Definition 

### ISSUE THREAD

**Issue by Karls-Developers** [unite-cms/unite-cms#379]
Hi,

i get the following Error if i try to see API Definition from graphiql view.
Can you reproduce this ?
Api Call is working fine only definition is not loading.
```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3d_images_wrapper" does not.
    at assertValidName (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:29084:11)
    at chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:14087:44
    at Array.forEach (<anonymous>)
    at GraphQLInputObjectType._defineFieldMap (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:14086:16)
    at GraphQLInputObjectType.getFields (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:14075:49)
    at typeMapReducer (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16618:26)
    at chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16621:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16619:28)
    at typeMapReducer (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/dist/chromeiql.js:16584:12)
```

**Comment by franzwilding** [comment]
Identifiers must start with a char (not a number). 
Is this a domain identifier? Or a field identifier?

How did you manage to save the domain config with this identifier?

**Comment by Karls-Developers** [comment]
I did not get any Error with saving this Variation Field.
Thanks for helping out ;-)

**Comment by franzwilding** [comment]
Thank you for reporting!

So the solution would be to start with a char. However I will add this as a bug issue, because the variant field should not be valid on domain create / update

**Comment by franzwilding** [comment]
> A better solution would be to use
> 
> ```sql
> JSON_EXTRACT(data, '$."$key"')
> ```
> 
> instead of
> 
> ```sql
> JSON_EXTRACT(data, '$.$key')
> ```

This is not relay an option here, because the official GraphQL specs do not allow identifiers with a number at the beginning: https://facebook.github.io/graphql/October2016/#sec-Names

The only solution would change the service paramerter `identifier_url_pattern` and `identifier_pattern` from: 

```
identifier_url_pattern: '^[a-z0-9]+[a-z0-9-_]*[a-z0-9]+$'
identifier_pattern: '^[a-z0-9]+[a-z0-9_]*[a-z0-9]+$'
```

to

```
identifier_url_pattern: '^[a-z]+[a-z0-9-_]*[a-z0-9]+$'
identifier_pattern: '^[a-z]+[a-z0-9_]*[a-z0-9]+$'
```

Because this is a breaking change, we can only change this with version 0.8

**Comment by franzwilding** [comment]
After considering this, we will change the validation in 0.7.4 and the url pattern in 0.8
